FROM php:7.2-fpm

MAINTAINER David Goring

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    apache2 \
    supervisor \
    libapache2-mod-xsendfile \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    libreadline-dev \
    libmcrypt-dev \
    libssh2-1-dev \
    libtidy-dev \
    zziplib-bin \
    libxml2-dev \
    libzip-dev \
    gnupg \
    msmtp \
    cron \
    git \
 && a2enmod \
    rewrite \
    actions \
    proxy_fcgi \
    alias \
    ssl \
    xsendfile

RUN openssl req -new -newkey rsa:4096 -nodes -x509 -days 365 \
    -subj "/C=GB/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" \
    -keyout /etc/ssl/certs/server.key \
    -out    /etc/ssl/certs/server.crt

RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
 && docker-php-ext-install \
    dom \
    exif \
    gd \
    iconv \
    mysqli \
    mbstring \
    pdo_mysql \
    tidy \
    zip \
 && pecl install ssh2-1.1.2 \
 && docker-php-ext-enable \
    ssh2

RUN curl -sS https://getcomposer.org/installer | php \
 && mv composer.phar /usr/bin/composer

COPY etc/ /etc

COPY site/ /site
RUN mkdir /config
COPY examples/apache.conf /config

RUN chown -Rf www-data.www-data /site /config

# Copy main script
COPY run.sh /run.sh
RUN chmod u+rwx /run.sh

EXPOSE 443

WORKDIR /site
ENTRYPOINT ["/run.sh"]
