FROM dgoring/php:7.2-fpm

MAINTAINER David Goring

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    nginx

RUN mkdir /var/client_body_temp

COPY etc/nginx/ /etc/nginx/
COPY etc/supervisor.d/nginx.ini /etc/supervisor.d/

COPY examples/nginx.conf /config
